services:

  proxy:
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik-certificates:/certificates
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.https.address=:443
      - --entrypoints.https.forwardedheaders.trustedips=${TRUSTED_PROXIES:-127.0.0.1/32}
      - --entrypoints.https.http.middlewares=hsts@docker
      - --entrypoints.https.http.tls.certresolver=le
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log

  db:
    restart: always

  backend:
    restart: always
    environment:
      FRONTEND_HOST: https://${DOMAIN:?Variable not set}
    labels:
      - traefik.http.middlewares.hsts.headers.stsseconds=31536000
      - traefik.http.middlewares.auth-ratelimit.ratelimit.sourcecriterion.ipstrategy.depth=${PROXY_HOPS:-0}

  frontend:
    restart: always

volumes:
  traefik-certificates:
