services:

  proxy:
    image: traefik:3.6
    ports:
      - "80:80"
      - "8090:8080"
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --log.level=WARN
      - --api
      - --api.insecure=true
  db:
    ports:
      - "5432:5432"
    command: postgres -c log_min_messages=warning

  adminer:
    ports:
      - "8080:8080"

  backend:
    ports:
      - "8000:8000"
    build:
      context: ../backend
      dockerfile: Dockerfile
    command:
      - fastapi
      - dev
      - --host
      - "0.0.0.0"
    healthcheck:
      interval: 10m
      start_interval: 1s
      start_period: 30s
    develop:
      watch:
        - path: ../backend
          action: sync
          target: /app
          ignore:
            - .venv
        - path: ../backend/pyproject.toml
          action: rebuild
    # TODO: remove once coverage is done locally
    volumes:
      - ../backend/htmlcov:/app/htmlcov
    environment:
      FASTAPI_ENV: "development"
      SMTP_HOST: "mailpit"
      SMTP_PORT: "1025"
      SMTP_TLS: "false"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: dev
    environment:
      NODE_ENV: "development"
    develop:
      watch:
        - action: sync
          path: ../frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ../frontend/package.json
        - action: rebuild
          path: ../frontend/bun.lock
    ports:
      - "3000:3000"

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_QUIET: "true"

  playwright:
    profiles: ["test"]
    build:
      context: ../frontend
      dockerfile: Dockerfile.playwright
      args:
        - NODE_ENV=production
    ipc: host
    depends_on:
      - backend
      - frontend
      - mailpit
    environment:
      - FIRST_SUPERUSER=${FIRST_SUPERUSER:?Variable not set}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD:?Variable not set}
      - PLAYWRIGHT_BASE_URL=http://frontend:3000
      - API_URL=http://backend:8000
      - MAILPIT_HOST=http://mailpit:8025
      - PLAYWRIGHT_HTML_HOST=0.0.0.0
      - CI=${CI:-}
    volumes:
      - ../frontend/blob-report:/app/blob-report
      - ../frontend/test-results:/app/test-results
    ports:
      - 9323:9323
