services:

  proxy:
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik-certificates:/certificates
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log

  db:
    restart: always

  adminer:
    restart: always
    labels:
      - traefik.http.routers.adminer-https.rule=Host(`adminer.${DOMAIN:?Variable not set}`)
      - traefik.http.routers.adminer-https.entrypoints=https
      - traefik.http.routers.adminer-https.tls=true
      - traefik.http.routers.adminer-https.tls.certresolver=le

  backend:
    restart: always
    environment:
      FRONTEND_HOST: https://${DOMAIN:?Variable not set}
    labels:
      - traefik.http.routers.backend-https.rule=Host(`${DOMAIN:?Variable not set}`) && (PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`))
      - traefik.http.routers.backend-https.entrypoints=https
      - traefik.http.routers.backend-https.tls=true
      - traefik.http.routers.backend-https.tls.certresolver=le

  frontend:
    restart: always
    labels:
      - traefik.http.routers.frontend-https.rule=Host(`${DOMAIN:?Variable not set}`)
      - traefik.http.routers.frontend-https.entrypoints=https
      - traefik.http.routers.frontend-https.tls=true
      - traefik.http.routers.frontend-https.tls.certresolver=le

volumes:
  traefik-certificates:
