// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import { type Client, type ClientMeta, type Options as Options2, type RequestResult, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { ItemsCreateItemData, ItemsCreateItemErrors, ItemsCreateItemResponses, ItemsDeleteItemData, ItemsDeleteItemErrors, ItemsDeleteItemResponses, ItemsReadItemData, ItemsReadItemErrors, ItemsReadItemResponses, ItemsReadItemsData, ItemsReadItemsErrors, ItemsReadItemsResponses, ItemsUpdateItemData, ItemsUpdateItemErrors, ItemsUpdateItemResponses, LoginLoginAccessTokenData, LoginLoginAccessTokenErrors, LoginLoginAccessTokenResponses, LoginRecoverPasswordData, LoginRecoverPasswordErrors, LoginRecoverPasswordResponses, LoginResetPasswordData, LoginResetPasswordErrors, LoginResetPasswordResponses, UsersCompleteSignupData, UsersCompleteSignupErrors, UsersCompleteSignupResponses, UsersConfirmEmailChangeData, UsersConfirmEmailChangeErrors, UsersConfirmEmailChangeResponses, UsersDeleteUserMeData, UsersDeleteUserMeErrors, UsersDeleteUserMeResponses, UsersReadUserMeData, UsersReadUserMeErrors, UsersReadUserMeResponses, UsersRegisterUserData, UsersRegisterUserErrors, UsersRegisterUserResponses, UsersRequestEmailChangeData, UsersRequestEmailChangeErrors, UsersRequestEmailChangeResponses, UsersUpdatePasswordMeData, UsersUpdatePasswordMeErrors, UsersUpdatePasswordMeResponses, UsersUpdateUserMeData, UsersUpdateUserMeErrors, UsersUpdateUserMeResponses, UtilsHealthCheckData, UtilsHealthCheckErrors, UtilsHealthCheckResponses } from './types.gen';
import { zItemsCreateItemBody, zItemsDeleteItemPath, zItemsReadItemPath, zItemsReadItemsQuery, zItemsUpdateItemBody, zItemsUpdateItemPath, zLoginLoginAccessTokenBody, zLoginRecoverPasswordBody, zLoginResetPasswordBody, zUsersCompleteSignupBody, zUsersConfirmEmailChangeBody, zUsersRegisterUserBody, zUsersRequestEmailChangeBody, zUsersUpdatePasswordMeBody, zUsersUpdateUserMeBody } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Read Items
 *
 * Retrieve items.
 */
export const itemsReadItems = <ThrowOnError extends boolean = false>(options?: Options<ItemsReadItemsData, ThrowOnError>): RequestResult<ItemsReadItemsResponses, ItemsReadItemsErrors, ThrowOnError> => (options?.client ?? client).get<ItemsReadItemsResponses, ItemsReadItemsErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: zItemsReadItemsQuery.optional()
    }).parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items',
    ...options
});

/**
 * Create Item
 *
 * Create new item.
 */
export const itemsCreateItem = <ThrowOnError extends boolean = false>(options: Options<ItemsCreateItemData, ThrowOnError>): RequestResult<ItemsCreateItemResponses, ItemsCreateItemErrors, ThrowOnError> => (options.client ?? client).post<ItemsCreateItemResponses, ItemsCreateItemErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zItemsCreateItemBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Item
 *
 * Delete an item.
 */
export const itemsDeleteItem = <ThrowOnError extends boolean = false>(options: Options<ItemsDeleteItemData, ThrowOnError>): RequestResult<ItemsDeleteItemResponses, ItemsDeleteItemErrors, ThrowOnError> => (options.client ?? client).delete<ItemsDeleteItemResponses, ItemsDeleteItemErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zItemsDeleteItemPath,
        query: z.never().optional()
    }).parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items/{id}',
    ...options
});

/**
 * Read Item
 *
 * Get item by ID.
 */
export const itemsReadItem = <ThrowOnError extends boolean = false>(options: Options<ItemsReadItemData, ThrowOnError>): RequestResult<ItemsReadItemResponses, ItemsReadItemErrors, ThrowOnError> => (options.client ?? client).get<ItemsReadItemResponses, ItemsReadItemErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: zItemsReadItemPath,
        query: z.never().optional()
    }).parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items/{id}',
    ...options
});

/**
 * Update Item
 *
 * Update an item.
 */
export const itemsUpdateItem = <ThrowOnError extends boolean = false>(options: Options<ItemsUpdateItemData, ThrowOnError>): RequestResult<ItemsUpdateItemResponses, ItemsUpdateItemErrors, ThrowOnError> => (options.client ?? client).patch<ItemsUpdateItemResponses, ItemsUpdateItemErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zItemsUpdateItemBody,
        path: zItemsUpdateItemPath,
        query: z.never().optional()
    }).parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/items/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login Access Token
 *
 * OAuth2 compatible token login, get an access token for future requests
 */
export const loginLoginAccessToken = <ThrowOnError extends boolean = false>(options: Options<LoginLoginAccessTokenData, ThrowOnError>): RequestResult<LoginLoginAccessTokenResponses, LoginLoginAccessTokenErrors, ThrowOnError> => (options.client ?? client).post<LoginLoginAccessTokenResponses, LoginLoginAccessTokenErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    requestValidator: async (data) => await z.object({
        body: zLoginLoginAccessTokenBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/v1/login/access-token',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Recover Password
 *
 * Password Recovery
 */
export const loginRecoverPassword = <ThrowOnError extends boolean = false>(options: Options<LoginRecoverPasswordData, ThrowOnError>): RequestResult<LoginRecoverPasswordResponses, LoginRecoverPasswordErrors, ThrowOnError> => (options.client ?? client).post<LoginRecoverPasswordResponses, LoginRecoverPasswordErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zLoginRecoverPasswordBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/v1/password-recovery',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset Password
 *
 * Reset password
 */
export const loginResetPassword = <ThrowOnError extends boolean = false>(options: Options<LoginResetPasswordData, ThrowOnError>): RequestResult<LoginResetPasswordResponses, LoginResetPasswordErrors, ThrowOnError> => (options.client ?? client).post<LoginResetPasswordResponses, LoginResetPasswordErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zLoginResetPasswordBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/v1/reset-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Confirm Email Change
 *
 * Apply a confirmed email change.
 */
export const usersConfirmEmailChange = <ThrowOnError extends boolean = false>(options: Options<UsersConfirmEmailChangeData, ThrowOnError>): RequestResult<UsersConfirmEmailChangeResponses, UsersConfirmEmailChangeErrors, ThrowOnError> => (options.client ?? client).post<UsersConfirmEmailChangeResponses, UsersConfirmEmailChangeErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zUsersConfirmEmailChangeBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/v1/users/confirm-email',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete User Me
 *
 * Delete own user.
 */
export const usersDeleteUserMe = <ThrowOnError extends boolean = false>(options?: Options<UsersDeleteUserMeData, ThrowOnError>): RequestResult<UsersDeleteUserMeResponses, UsersDeleteUserMeErrors, ThrowOnError> => (options?.client ?? client).delete<UsersDeleteUserMeResponses, UsersDeleteUserMeErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options
});

/**
 * Read User Me
 *
 * Get current user.
 */
export const usersReadUserMe = <ThrowOnError extends boolean = false>(options?: Options<UsersReadUserMeData, ThrowOnError>): RequestResult<UsersReadUserMeResponses, UsersReadUserMeErrors, ThrowOnError> => (options?.client ?? client).get<UsersReadUserMeResponses, UsersReadUserMeErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options
});

/**
 * Update User Me
 *
 * Update own user.
 */
export const usersUpdateUserMe = <ThrowOnError extends boolean = false>(options: Options<UsersUpdateUserMeData, ThrowOnError>): RequestResult<UsersUpdateUserMeResponses, UsersUpdateUserMeErrors, ThrowOnError> => (options.client ?? client).patch<UsersUpdateUserMeResponses, UsersUpdateUserMeErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zUsersUpdateUserMeBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Request Email Change
 *
 * Request the link that confirms a new email address.
 */
export const usersRequestEmailChange = <ThrowOnError extends boolean = false>(options: Options<UsersRequestEmailChangeData, ThrowOnError>): RequestResult<UsersRequestEmailChangeResponses, UsersRequestEmailChangeErrors, ThrowOnError> => (options.client ?? client).post<UsersRequestEmailChangeResponses, UsersRequestEmailChangeErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zUsersRequestEmailChangeBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me/email',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update Password Me
 *
 * Update own password.
 */
export const usersUpdatePasswordMe = <ThrowOnError extends boolean = false>(options: Options<UsersUpdatePasswordMeData, ThrowOnError>): RequestResult<UsersUpdatePasswordMeResponses, UsersUpdatePasswordMeErrors, ThrowOnError> => (options.client ?? client).patch<UsersUpdatePasswordMeResponses, UsersUpdatePasswordMeErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zUsersUpdatePasswordMeBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register User
 *
 * Request the link that completes a sign-up.
 */
export const usersRegisterUser = <ThrowOnError extends boolean = false>(options: Options<UsersRegisterUserData, ThrowOnError>): RequestResult<UsersRegisterUserResponses, UsersRegisterUserErrors, ThrowOnError> => (options.client ?? client).post<UsersRegisterUserResponses, UsersRegisterUserErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zUsersRegisterUserBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/v1/users/signup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Complete Signup
 *
 * Create the user a sign-up link was sent for.
 */
export const usersCompleteSignup = <ThrowOnError extends boolean = false>(options: Options<UsersCompleteSignupData, ThrowOnError>): RequestResult<UsersCompleteSignupResponses, UsersCompleteSignupErrors, ThrowOnError> => (options.client ?? client).post<UsersCompleteSignupResponses, UsersCompleteSignupErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: zUsersCompleteSignupBody,
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/v1/users/signup/complete',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health Check
 *
 * Report whether the API can serve requests.
 */
export const utilsHealthCheck = <ThrowOnError extends boolean = false>(options?: Options<UtilsHealthCheckData, ThrowOnError>): RequestResult<UtilsHealthCheckResponses, UtilsHealthCheckErrors, ThrowOnError> => (options?.client ?? client).get<UtilsHealthCheckResponses, UtilsHealthCheckErrors, ThrowOnError>({
    requestValidator: async (data) => await z.object({
        body: z.never().optional(),
        path: z.never().optional(),
        query: z.never().optional()
    }).parseAsync(data),
    url: '/api/v1/utils/health-check',
    ...options
});
