// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccountDeletion
 */
export type AccountDeletion = {
    /**
     * Current Password
     */
    current_password: string;
};

/**
 * ChatMessagePublic
 */
export type ChatMessagePublic = {
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: 'user' | 'assistant';
};

/**
 * ChatMessagesPublic
 */
export type ChatMessagesPublic = {
    /**
     * Count
     */
    count: number;
    /**
     * Data
     */
    data: Array<ChatMessagePublic>;
};

/**
 * ChatRun
 */
export type ChatRun = {
    /**
     * Messages
     */
    messages: Array<ChatRunMessage>;
    /**
     * Runid
     */
    runId: string;
    /**
     * Threadid
     */
    threadId: string;
};

/**
 * ChatRunMessage
 */
export type ChatRunMessage = {
    /**
     * Content
     */
    content?: unknown;
    /**
     * Role
     */
    role: string;
};

/**
 * ConversationPublic
 */
export type ConversationPublic = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string | null;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ConversationsPublic
 */
export type ConversationsPublic = {
    /**
     * Count
     */
    count: number;
    /**
     * Data
     */
    data: Array<ConversationPublic>;
};

/**
 * Credentials
 */
export type Credentials = {
    /**
     * Password
     */
    password: string;
    /**
     * Username
     */
    username: string;
};

/**
 * EmailChange
 */
export type EmailChange = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * Email
     */
    email: string;
};

/**
 * EmailChangeConfirm
 */
export type EmailChangeConfirm = {
    /**
     * Token
     */
    token: string;
};

/**
 * HTTPError
 */
export type HttpError = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Title
     */
    title: string;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Title
     */
    title: string;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Title
     */
    title?: string;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Count
     */
    count: number;
    /**
     * Data
     */
    data: Array<ItemPublic>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * New Password
     */
    new_password: string;
    /**
     * Token
     */
    token: string;
};

/**
 * PasswordRecovery
 */
export type PasswordRecovery = {
    /**
     * Email
     */
    email: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Expires In
     */
    expires_in: number;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ChatRunChatData = {
    body: ChatRun;
    path?: never;
    query?: never;
    url: '/api/v1/chat';
};

export type ChatRunChatErrors = {
    /**
     * Bad Request
     */
    400: HttpError;
    /**
     * Unauthorized
     */
    401: HttpError;
    /**
     * Forbidden
     */
    403: HttpError;
    /**
     * Not Found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: HttpError;
    /**
     * Service Unavailable
     */
    503: HttpError;
};

export type ChatRunChatError = ChatRunChatErrors[keyof ChatRunChatErrors];

export type ChatRunChatResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChatReadConversationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/chat/conversations';
};

export type ChatReadConversationsErrors = {
    /**
     * Unauthorized
     */
    401: HttpError;
    /**
     * Forbidden
     */
    403: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatReadConversationsError = ChatReadConversationsErrors[keyof ChatReadConversationsErrors];

export type ChatReadConversationsResponses = {
    /**
     * Successful Response
     */
    200: ConversationsPublic;
};

export type ChatReadConversationsResponse = ChatReadConversationsResponses[keyof ChatReadConversationsResponses];

export type ChatCreateConversationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/chat/conversations';
};

export type ChatCreateConversationErrors = {
    /**
     * Unauthorized
     */
    401: HttpError;
    /**
     * Forbidden
     */
    403: HttpError;
};

export type ChatCreateConversationError = ChatCreateConversationErrors[keyof ChatCreateConversationErrors];

export type ChatCreateConversationResponses = {
    /**
     * Successful Response
     */
    201: ConversationPublic;
};

export type ChatCreateConversationResponse = ChatCreateConversationResponses[keyof ChatCreateConversationResponses];

export type ChatReadConversationData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/chat/conversations/{id}';
};

export type ChatReadConversationErrors = {
    /**
     * Unauthorized
     */
    401: HttpError;
    /**
     * Forbidden
     */
    403: HttpError;
    /**
     * Not Found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatReadConversationError = ChatReadConversationErrors[keyof ChatReadConversationErrors];

export type ChatReadConversationResponses = {
    /**
     * Successful Response
     */
    200: ConversationPublic;
};

export type ChatReadConversationResponse = ChatReadConversationResponses[keyof ChatReadConversationResponses];

export type ChatReadMessagesData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/chat/conversations/{id}/messages';
};

export type ChatReadMessagesErrors = {
    /**
     * Unauthorized
     */
    401: HttpError;
    /**
     * Forbidden
     */
    403: HttpError;
    /**
     * Not Found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatReadMessagesError = ChatReadMessagesErrors[keyof ChatReadMessagesErrors];

export type ChatReadMessagesResponses = {
    /**
     * Successful Response
     */
    200: ChatMessagesPublic;
};

export type ChatReadMessagesResponse = ChatReadMessagesResponses[keyof ChatReadMessagesResponses];

export type ItemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items';
};

export type ItemsReadItemsErrors = {
    /**
     * Unauthorized
     */
    401: HttpError;
    /**
     * Forbidden
     */
    403: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemsError = ItemsReadItemsErrors[keyof ItemsReadItemsErrors];

export type ItemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type ItemsReadItemsResponse = ItemsReadItemsResponses[keyof ItemsReadItemsResponses];

export type ItemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items';
};

export type ItemsCreateItemErrors = {
    /**
     * Unauthorized
     */
    401: HttpError;
    /**
     * Forbidden
     */
    403: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsCreateItemError = ItemsCreateItemErrors[keyof ItemsCreateItemErrors];

export type ItemsCreateItemResponses = {
    /**
     * Successful Response
     */
    201: ItemPublic;
};

export type ItemsCreateItemResponse = ItemsCreateItemResponses[keyof ItemsCreateItemResponses];

export type ItemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsDeleteItemErrors = {
    /**
     * Unauthorized
     */
    401: HttpError;
    /**
     * Forbidden
     */
    403: HttpError;
    /**
     * Not Found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsDeleteItemError = ItemsDeleteItemErrors[keyof ItemsDeleteItemErrors];

export type ItemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ItemsDeleteItemResponse = ItemsDeleteItemResponses[keyof ItemsDeleteItemResponses];

export type ItemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsReadItemErrors = {
    /**
     * Unauthorized
     */
    401: HttpError;
    /**
     * Forbidden
     */
    403: HttpError;
    /**
     * Not Found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemError = ItemsReadItemErrors[keyof ItemsReadItemErrors];

export type ItemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsReadItemResponse = ItemsReadItemResponses[keyof ItemsReadItemResponses];

export type ItemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsUpdateItemErrors = {
    /**
     * Unauthorized
     */
    401: HttpError;
    /**
     * Forbidden
     */
    403: HttpError;
    /**
     * Not Found
     */
    404: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsUpdateItemError = ItemsUpdateItemErrors[keyof ItemsUpdateItemErrors];

export type ItemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsUpdateItemResponse = ItemsUpdateItemResponses[keyof ItemsUpdateItemResponses];

export type LoginLoginAccessTokenData = {
    body: Credentials;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Bad Request
     */
    400: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: HttpError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/logout';
};

export type LoginLogoutErrors = {
    /**
     * Unauthorized
     */
    401: HttpError;
    /**
     * Forbidden
     */
    403: HttpError;
};

export type LoginLogoutError = LoginLogoutErrors[keyof LoginLogoutErrors];

export type LoginLogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LoginLogoutResponse = LoginLogoutResponses[keyof LoginLogoutResponses];

export type LoginRecoverPasswordData = {
    body: PasswordRecovery;
    path?: never;
    query?: never;
    url: '/api/v1/password-recovery';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password';
};

export type LoginResetPasswordErrors = {
    /**
     * Bad Request
     */
    400: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type UsersConfirmEmailChangeData = {
    body: EmailChangeConfirm;
    path?: never;
    query?: never;
    url: '/api/v1/users/confirm-email';
};

export type UsersConfirmEmailChangeErrors = {
    /**
     * Bad Request
     */
    400: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersConfirmEmailChangeError = UsersConfirmEmailChangeErrors[keyof UsersConfirmEmailChangeErrors];

export type UsersConfirmEmailChangeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersConfirmEmailChangeResponse = UsersConfirmEmailChangeResponses[keyof UsersConfirmEmailChangeResponses];

export type UsersDeleteUserMeData = {
    body: AccountDeletion;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeErrors = {
    /**
     * Bad Request
     */
    400: HttpError;
    /**
     * Unauthorized
     */
    401: HttpError;
    /**
     * Forbidden
     */
    403: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: HttpError;
};

export type UsersDeleteUserMeError = UsersDeleteUserMeErrors[keyof UsersDeleteUserMeErrors];

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeErrors = {
    /**
     * Unauthorized
     */
    401: HttpError;
    /**
     * Forbidden
     */
    403: HttpError;
};

export type UsersReadUserMeError = UsersReadUserMeErrors[keyof UsersReadUserMeErrors];

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Unauthorized
     */
    401: HttpError;
    /**
     * Forbidden
     */
    403: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersRequestEmailChangeData = {
    body: EmailChange;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/email';
};

export type UsersRequestEmailChangeErrors = {
    /**
     * Bad Request
     */
    400: HttpError;
    /**
     * Unauthorized
     */
    401: HttpError;
    /**
     * Forbidden
     */
    403: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: HttpError;
};

export type UsersRequestEmailChangeError = UsersRequestEmailChangeErrors[keyof UsersRequestEmailChangeErrors];

export type UsersRequestEmailChangeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersRequestEmailChangeResponse = UsersRequestEmailChangeResponses[keyof UsersRequestEmailChangeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Bad Request
     */
    400: HttpError;
    /**
     * Unauthorized
     */
    401: HttpError;
    /**
     * Forbidden
     */
    403: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Too Many Requests
     */
    429: HttpError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UsersCompleteSignupData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup/complete';
};

export type UsersCompleteSignupErrors = {
    /**
     * Bad Request
     */
    400: HttpError;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCompleteSignupError = UsersCompleteSignupErrors[keyof UsersCompleteSignupErrors];

export type UsersCompleteSignupResponses = {
    /**
     * Successful Response
     */
    201: UserPublic;
};

export type UsersCompleteSignupResponse = UsersCompleteSignupResponses[keyof UsersCompleteSignupResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check';
};

export type UtilsHealthCheckErrors = {
    /**
     * Service Unavailable
     */
    503: HttpError;
};

export type UtilsHealthCheckError = UtilsHealthCheckErrors[keyof UtilsHealthCheckErrors];

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];
