// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Body_login-login_access_token
 */
export const zBodyLoginLoginAccessToken = z.object({
    client_id: z.string().nullish(),
    client_secret: z.string().nullish(),
    grant_type: z.string().regex(/^password$/).nullish(),
    password: z.string(),
    scope: z.string().optional().default(''),
    username: z.string()
});

/**
 * HTTPError
 */
export const zHttpError = z.object({
    detail: z.string()
});

/**
 * ItemCreate
 */
export const zItemCreate = z.object({
    description: z.string().max(255).nullish(),
    title: z.string().min(1).max(255)
});

/**
 * ItemPublic
 */
export const zItemPublic = z.object({
    created_at: z.iso.datetime().nullish(),
    description: z.string().max(255).nullish(),
    id: z.uuid(),
    owner_id: z.uuid(),
    title: z.string().min(1).max(255)
});

/**
 * ItemUpdate
 */
export const zItemUpdate = z.object({
    description: z.string().max(255).nullish(),
    title: z.string().min(1).max(255).nullish()
});

/**
 * ItemsPublic
 */
export const zItemsPublic = z.object({
    count: z.int(),
    data: z.array(zItemPublic)
});

/**
 * Message
 */
export const zMessage = z.object({
    message: z.string()
});

/**
 * NewPassword
 */
export const zNewPassword = z.object({
    new_password: z.string().min(8).max(128),
    token: z.string()
});

/**
 * Token
 */
export const zToken = z.object({
    access_token: z.string(),
    expires_in: z.int(),
    token_type: z.string().optional().default('bearer')
});

/**
 * UpdatePassword
 */
export const zUpdatePassword = z.object({
    current_password: z.string().min(8).max(128),
    new_password: z.string().min(8).max(128)
});

/**
 * UserPublic
 */
export const zUserPublic = z.object({
    created_at: z.iso.datetime().nullish(),
    email: z.email().max(255),
    full_name: z.string().min(1).max(255),
    id: z.uuid(),
    is_active: z.boolean().optional().default(true),
    is_superuser: z.boolean().optional().default(false)
});

/**
 * UserRegister
 */
export const zUserRegister = z.object({
    email: z.email().max(255),
    full_name: z.string().min(1).max(255),
    password: z.string().min(8).max(128)
});

/**
 * UserUpdateMe
 */
export const zUserUpdateMe = z.object({
    email: z.email().max(255).nullish(),
    full_name: z.string().min(1).max(255).nullish()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    ctx: z.record(z.string(), z.unknown()).optional(),
    input: z.unknown().optional(),
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

export const zItemsReadItemsQuery = z.object({
    skip: z.int().optional().default(0),
    limit: z.int().optional().default(100)
});

export const zItemsCreateItemBody = zItemCreate;

export const zItemsDeleteItemPath = z.object({
    id: z.uuid()
});

export const zItemsReadItemPath = z.object({
    id: z.uuid()
});

export const zItemsUpdateItemBody = zItemUpdate;

export const zItemsUpdateItemPath = z.object({
    id: z.uuid()
});

export const zLoginLoginAccessTokenBody = zBodyLoginLoginAccessToken;

export const zLoginRecoverPasswordPath = z.object({
    email: z.string()
});

export const zLoginResetPasswordBody = zNewPassword;

export const zUsersUpdateUserMeBody = zUserUpdateMe;

export const zUsersUpdatePasswordMeBody = zUpdatePassword;

export const zUsersRegisterUserBody = zUserRegister;
