// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * AccountDeletion
 */
export const zAccountDeletion = z.object({
    current_password: z.string().min(1).max(128)
});

/**
 * Credentials
 */
export const zCredentials = z.object({
    password: z.string().min(1).max(128),
    username: z.string().max(255).regex(/^[A-Za-z0-9_'+-]+(\.[A-Za-z0-9_'+-]+)*@([A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?\.)+[A-Za-z]{2,}$/)
});

/**
 * EmailChange
 */
export const zEmailChange = z.object({
    current_password: z.string().min(1).max(128),
    email: z.string().max(255).regex(/^[A-Za-z0-9_'+-]+(\.[A-Za-z0-9_'+-]+)*@([A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?\.)+[A-Za-z]{2,}$/)
});

/**
 * EmailChangeConfirm
 */
export const zEmailChangeConfirm = z.object({
    token: z.string()
});

/**
 * HTTPError
 */
export const zHttpError = z.object({
    detail: z.string()
});

/**
 * ItemCreate
 */
export const zItemCreate = z.object({
    description: z.string().max(255).nullish(),
    title: z.string().min(1).max(255)
});

/**
 * ItemPublic
 */
export const zItemPublic = z.object({
    created_at: z.iso.datetime(),
    description: z.string().nullable(),
    id: z.uuid(),
    owner_id: z.uuid(),
    title: z.string()
});

/**
 * ItemUpdate
 */
export const zItemUpdate = z.object({
    description: z.string().max(255).nullish(),
    title: z.string().min(1).max(255).optional()
});

/**
 * ItemsPublic
 */
export const zItemsPublic = z.object({
    count: z.int(),
    data: z.array(zItemPublic)
});

/**
 * Message
 */
export const zMessage = z.object({
    message: z.string()
});

/**
 * NewPassword
 */
export const zNewPassword = z.object({
    new_password: z.string().min(8).max(128),
    token: z.string()
});

/**
 * PasswordRecovery
 */
export const zPasswordRecovery = z.object({
    email: z.string().max(255).regex(/^[A-Za-z0-9_'+-]+(\.[A-Za-z0-9_'+-]+)*@([A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?\.)+[A-Za-z]{2,}$/)
});

/**
 * Token
 */
export const zToken = z.object({
    access_token: z.string(),
    expires_in: z.int(),
    token_type: z.string()
});

/**
 * UpdatePassword
 */
export const zUpdatePassword = z.object({
    current_password: z.string().min(1).max(128),
    new_password: z.string().min(8).max(128)
});

/**
 * UserPublic
 */
export const zUserPublic = z.object({
    created_at: z.iso.datetime(),
    email: z.string(),
    full_name: z.string(),
    id: z.uuid(),
    is_active: z.boolean(),
    is_superuser: z.boolean()
});

/**
 * UserRegister
 */
export const zUserRegister = z.object({
    email: z.string().max(255).regex(/^[A-Za-z0-9_'+-]+(\.[A-Za-z0-9_'+-]+)*@([A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?\.)+[A-Za-z]{2,}$/),
    full_name: z.string().min(1).max(255)
});

/**
 * UserUpdateMe
 */
export const zUserUpdateMe = z.object({
    full_name: z.string().min(1).max(255).optional()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    ctx: z.record(z.string(), z.unknown()).optional(),
    input: z.unknown().optional(),
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

export const zItemsReadItemsQuery = z.object({
    skip: z.int().gte(0).optional().default(0),
    limit: z.int().gte(1).lte(100).optional().default(100)
});

export const zItemsCreateItemBody = zItemCreate;

export const zItemsDeleteItemPath = z.object({
    id: z.uuid()
});

export const zItemsReadItemPath = z.object({
    id: z.uuid()
});

export const zItemsUpdateItemBody = zItemUpdate;

export const zItemsUpdateItemPath = z.object({
    id: z.uuid()
});

export const zLoginLoginAccessTokenBody = zCredentials;

export const zLoginRecoverPasswordBody = zPasswordRecovery;

export const zLoginResetPasswordBody = zNewPassword;

export const zUsersConfirmEmailChangeBody = zEmailChangeConfirm;

export const zUsersDeleteUserMeBody = zAccountDeletion;

export const zUsersUpdateUserMeBody = zUserUpdateMe;

export const zUsersRequestEmailChangeBody = zEmailChange;

export const zUsersUpdatePasswordMeBody = zUpdatePassword;

export const zUsersRegisterUserBody = zUserRegister;

export const zUsersCompleteSignupBody = zNewPassword;
